FROM oraclelinux:9
MAINTAINER Sergey Nartimov <just.lest@gmail.com>

RUN dnf install -y yum-utils rpm-build rpm-sign redhat-rpm-config rpmdevtools createrepo systemd-rpm-macros && \
  dnf clean all
RUN echo '%_topdir /rpmbuild' > /root/.rpmmacros

WORKDIR /rpmbuild

ADD bin/build-spec /usr/local/bin/build-spec
